# Generated by Django 5.0.1 on 2024-01-16 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_loggin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='otp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
