# Generated by Django 5.0.3 on 2024-04-07 19:29

import custom_loggin.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_loggin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, verbose_name=custom_loggin.models.MyUser),
        ),
    ]
