# Generated by Django 5.0.3 on 2024-04-09 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_loggin', '0004_remove_profile_user_remove_myuser_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MyUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
