# Generated by Django 5.0.1 on 2024-01-18 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='\\myshop\\staticfiles\x07dmin\\img/image.jpg', upload_to='product_images/'),
        ),
    ]
