# Generated by Django 5.0.1 on 2024-01-18 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default='arayeshi', on_delete=django.db.models.deletion.CASCADE, to='products.category'),
        ),
    ]
