# Generated by Django 5.0.1 on 2024-01-26 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_loggin', '0003_customer'),
        ('products', '0007_customer_alter_product_image_alter_product_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_loggin.customer'),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
